### ISSUE TITLE
Add charts to spreadsheet

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#100]
**http://stackoverflow.com/q/39636138/4548500**
http://stackoverflow.com/q/21855842/4548500
http://stackoverflow.com/q/29014848/4548500
http://stackoverflow.com/q/38913412/4548500
https://github.com/chhunchha/Excel-Chart-Using-Java/blob/master/src/com/programmingfree/excelexamples/CreateExcelFile.java#L226

### Team sheets

- Counter metrics in a line plot
- Stopwatch metrics in another line plot

### Average sheet

- Graph each column in a scatter plot. Ideally it would be a bar chart to compare all the teams, but Apache Poi doesn't support that.

**Comment by blake1029384756** [comment]
I love this idea! Visuals always help me view data

**Comment by SUPERCILEX** [comment]
@blake1029384756 Would you be willing to share screenshots of what the graphs look like in [this sheet](https://drive.google.com/open?id=0B2y2uzttQJ1EdV9kd2Q1QUd3d2M)? I can't get the legend labels to show up and I'm not sure if it's a Google Sheets problem or a code problem. Thanks!

**Comment by blake1029384756** [comment]
I got an error when trying to open it up. It said the file had an error and wanted to know if it should recover the data, so I said yes and this is the result. The log file it links to says the same thing. 

![Imgur](http://i.imgur.com/OGkdJye.png)

**Comment by blake1029384756** [comment]
There is also not any charts in the document. Are they suppose to be on the Team Averages page?

**Comment by SUPERCILEX** [comment]
@blake1029384756 Hmmm, thanks for looking into this. The charts are loading in Google Sheets so I'm guessing the reason the legends aren't showing up is because they're half-broken. It's also broken in Excel online so when I get it working there I'll report back to you. Anyway, thanks again!

**Comment by SUPERCILEX** [comment]
@blake1029384756 I finally got it working in Excel online so I'm guessing you won't have any problems now. Here's an [example spreadsheet](https://drive.google.com/file/d/0B2y2uzttQJ1EUDFRY1FVdzNPazQ/view?usp=sharing) if you want to try it out.

I'm really happy with the individual team sheet charts, but work is still progressing for the main average chart: #106.
