### ISSUE TITLE
New Build Server

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#105]
Right now you are using Travis and it works pretty well but doesn't provide an apk. I propose you switch to using Jenkins. It does the same things as Travis except it also provides an apk. This would be useful for testers if you needed things tested on different branches.
https://jenkins.io/ 

Here is an example of how someone implemented it
http://www.snapprefs-builds.com/

**Comment by SUPERCILEX** [comment]
@blake1029384756 Travis CI is a hosted service whereas Jenkins is a self-hosted meaning I would have to have my own server (which I don't). As for testing it would be way quicker​ and easier to just build and deploy locally.

PS: if you're looking for release apks, check out my repo for that: https://github.com/SUPERCILEX/app-version-history/commits/master.
