### ISSUE TITLE
Improve average sheet chart

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#106]
![untitled](https://cloud.githubusercontent.com/assets/9490724/24824510/3d9f0a9e-1bc1-11e7-8ff5-292595286423.png)

**Comment by blake1029384756** [comment]
Could you also improve the charts on the team sheets? They are overlapping each other making them hard to read. This has the sane effect in both excel and google sheets.
![Imgur](http://i.imgur.com/LfN9DSv.png)

This is how it should be. 
![Imgur](http://i.imgur.com/zAXWSn1.png)

**Comment by SUPERCILEX** [comment]
@blake1029384756 moved your comment to #112. Also, it's fixed in the latest dev build! 🎉

**Comment by blake1029384756** [comment]
Sweet! Cheers! 🎉

**Comment by SUPERCILEX** [comment]
I just had an idea that would fix these issues while not having to deal with them directly. Since none of the data is inherently related, it doesn't really make sense to put it all in chart. _Sooo_, the solution is to make one chart per metric. This would fix the scale issue and the labels at the bottom (because the title of the chart would be the metric name). As for showing the values, screw that. 😀 I think the values will be visible enough and it would be too much of a pain to figure out.
