### ISSUE TITLE
Crash when taking picture

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#111]
When I try to take a picture the app crashes. From what I can tell from the log, the app didn't have permission to use the camera. 

Edit:
I fixed this by manually enabling the camera permission for the app. Does this happen to everyone? If so you should find out why the permission wasn't enabled by default. An average user won't know how to do this by themselves.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Ouch! 😢 I'm so confused right now. Late last night I added the camera permissions to the manifest because I felt like it was wrong to not have it. The WTF thing is that without the permission, I didn't get a security exception, but with the permission, the app started crashing. Anyway, I've fixed, but it doesn't make any sense. Maybe a security hole in Android? (That's unlikely) IDK, anyway, it's fixed.

**Comment by SUPERCILEX** [comment]
Nevermind, I'm still seeing the crash.

**Comment by vannaka** [comment]
@SUPERCILIX, does the crash only happen on Nougat devices? I know on Android 7.X they introduced a new permissions system.

**Comment by blake1029384756** [comment]
@vannaka no, I'm on android 6.0.1

**Comment by blake1029384756** [comment]
Here is the log from the crash
[mediacrash.txt](https://github.com/SUPERCILEX/Robot-Scouter/files/923811/mediacrash.txt)

**Comment by SUPERCILEX** [comment]
@blake1029384756 @vannaka Don't worry guys! 😄 I've just been trying to do a lot of stuff at once, should be fine now. @vannaka Yeah, I get the crashes in Firebase, but thanks anyway! @vannaka Yeah, the new permission stuff happened in 6.x (Marshmellow) and I'm already setup for that with spreadsheet exporting. I just made a bunch of typos! 🤣

**Comment by blake1029384756** [comment]
@SUPERCILEX just trying to give as much info as I can to be of some help. Haha, gl finding them

**Comment by SUPERCILEX** [comment]
Ok, this should work! 🚀 We'll see once the build finishes, but basically I made a bunch of typos when requesting the permissions. 😄

**Comment by SUPERCILEX** [comment]
@blake1029384756 Yeah, it's totally fine!

**Comment by blake1029384756** [comment]
It works! Congrats!

**Comment by SUPERCILEX** [comment]
Just updated RS on my Pixel and yup, it worked! 😁 Thank you guys being alpha testers and gently telling me when I'm being stupid. 🤣
