### ISSUE TITLE
Team charts overlap each other

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#112]
From @blake1029384756:
> @SUPERCILEX Could you also improve the charts on the team sheets? They are overlapping each other making them hard to read. This has the same effect in both excel and google sheets.
![Imgur](http://i.imgur.com/LfN9DSv.png)

This is how it should be. 
![Imgur](http://i.imgur.com/zAXWSn1.png)

**Comment by blake1029384756** [comment]
@SUPERCILEX The graphs still overlap in excel but are fixed on google sheets

**Comment by SUPERCILEX** [comment]
@blake1029384756 Aw dang, the inconsistency between Google Sheets and Excel can be really frustrating sometimes. Anyway, now that the infrastructure is setup, it's just a one line of code change: I had a `-1` [in the wrong place](https://github.com/SUPERCILEX/Robot-Scouter/commit/94b54894ca7bb4b7e4589a1d2d1369deea36f960#diff-4dc59a6a2fd350fb1012cc3f9f9a7b56R724). Thanks for the tip! 😄

**Comment by SUPERCILEX** [comment]
@blake1029384756 The update just went live, is it fixed for you?

**Comment by blake1029384756** [comment]
@SUPERCILEX looks good! Thanks!

**Comment by SUPERCILEX** [comment]
Awesome!
