### ISSUE TITLE
Import teams from event

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#158]
Before an event (when we have internet connection) we should be able to type in the event code and import the teams for a specific event, along with their TBA information. Couldn't find if this was implemented anywhere, or if it's supposed to be done in another way, but it seems like it could be pretty useful.

**Comment by andrewda** [comment]
Teams at event in TBA APIv3: https://www.thebluealliance.com/api/v3/event/2017orwil/teams

**Comment by SUPERCILEX** [comment]
@andrewda Yep, this is going to be implemented in #55.

Right now, all the ideas are in my head, but I'm planning on completely revolutionizing scouting. 😄 As a general overview, I want a massively integrated flow from generating the rotation schedule to automatically exporting scouting data at the end of the day. If I can do it right, it'll completely crush the competition and forever lock people into the Robot Scouter ecosystem. When I'm done, I'll have a hardcore document similar to #82.

**Comment by andrewda** [comment]
> If I can do it right, it'll completely crush the competition and forever lock people into the Robot Scouter ecosystem.

Damn those sound like some good ideas!

**Comment by blake1029384756** [comment]
Might want to check this out

Roblu Scouting System Complete

https://www.reddit.com/r/FRC/comments/6tl0mz/roblu_scouting_system_complete/

**Comment by SUPERCILEX** [comment]
@blake1029384756 Yeah, I saw that but it's going to be a [subscription model](https://www.roblu.net/purchase/) so lol. $100 bucks for the source code? Every other app out there is free and open-source! Anyway, I don't want to share too many details until I'm ready, but I think Robot Scouter will have a far superior flow and integration.

**Comment by andrewda** [comment]
And syncing across devices costs more? 🤔  That seems like a pretty basic thing that should come included, especially if you're _paying_ for the app! I can't really see anyone using it when it's obviously only for the profit. 

Also why in the world is the lowest option for the subscription 6 months? Competition season is at most 3 months... I'm so confused by their model.

**Comment by andrewda** [comment]
And they ask for sponsors? Who's going to sponsor you for $35 when you're literally selling a product? So many questions!

**Comment by SUPERCILEX** [comment]
@andrewda lol, that's some hardcore tash talking! 😂 Here's my professional statement for the day:
> Robot Scouter is open to and encourages competition. We believe the customer benefits from a broad set of choices and we strive to build the best possible choice.

😂

**Comment by SUPERCILEX** [comment]
@blake1029384756 thanks for the tip! 😄

**Comment by andrewda** [comment]
@SUPERCILEX not trying to trash talk... just honestly confused. I can't see them making nearly as much money as they would from donations if the app was free.

**Comment by SUPERCILEX** [comment]
@andrewda true, maybe they want to see what setting up a business is like? Or they just want to scam one person? Or maybe we're just noobs and teams will actually pay for this stuff? Yeah, I'm not sure.

**Comment by andrewda** [comment]
> Or maybe we're just noobs and teams will actually pay for this stuff?

$99.99 for Robot-Scouter. GO! GO! GO!

**Comment by SUPERCILEX** [comment]
😂
