### ISSUE TITLE
Calculate team OPR's (or some other ranking stat)

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#159]
It would be cool to show some kind of contribution statistic based on the scouted data. OPR might not be the best way to go about this, though, if we can get more accurate measures by estimating the contribution from each team. This could get a little complicated, but here's kinda what I'm envisioning:

When scouting a team, we can estimate the percentage of the points scored by a specific team (along with entering the final score of the match). This would require RS being more match-oriented, which could help clean some stuff up (multiple scouts per match, for example), but may also complicate some other things. Anyways, if I'm scouting team 2521, for example, I could say they contributed 50% of the alliance's 200 points. From that, we can assume they contributed 100 points. If the other two teams aren't scouted, we can assume they each scored 25%, or 50 points (if they are scouted, simply use the scouted estimate). We keep a running total point contribution estimates, and divide them by the total number of matches to get a specific team's contribution score. Also, if a team is scouted multiple times for a given match, use the average of the contribution estimates.

OPR should also be shown for comparison.

**Comment by SUPERCILEX** [comment]
What do you mean by "multiple scouts per match"? RS doesn't prevent you from scouting a team several times per match.

As for the idea, sounds cool! The beauty of RS is that none of this has to be built-in. For your idea, with the existing codebase we can simply add a counter metric with a `%` unit and ask scouters to enter a number from 0-100. And the export spreadsheet already does averages by the number of scouts (which is effectively the same as dividing by the number of matches).

I'm going to keep this issue open to **remind myself to add an OPR-ish metric to default match scouting template for next year**.

As for usability, I've created #162 which would make choosing a range much easier.

**Comment by andrewda** [comment]
Yea OPR is a lot more difficult to calculate than just averaging some stuff, but should be doable fairly easily.

**Comment by SUPERCILEX** [comment]
I've added an "Approximate contribution to overall score" metric for the BunnyBots match scouting template. And #162 is being tracked so I'm going to close this.

**Comment by andrewda** [comment]
Sweet! Do you think the app might eventually integrate with TBA enough to download actual match data, such as score, and use the scouted contribution values to calculate an OPR-like metric? Or should I make a little tool that takes an exported Robot-Scouter spreadsheet and do these calculations?

**Comment by SUPERCILEX** [comment]
@andrewda I think you would have to go through the spreadsheet since the OPR metric doesn't get special treatment.
