### ISSUE TITLE
Add option to terminate stopwatch without saving lap

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#181]
### Step 1: Describe your environment

- Robot Scouter version: 2.1.0.5721
- Android OS version: 22
- User id: TqIcDU3KvjgZedtvrw6QdADzwTv1

### Step 2: Describe the problem:
We were getting some unusually high stopwatch counter numbers in our data and discovered that if the user forgets to press stop on the stopwatch function, the stopwatch feature will keep going/counting even if the user is no longer in that scout. Is there a way to fix this?

## @SUPERCILEX here

Make long-press on stop button cancel without saving, but also add an undo button that continues the ticker. As a bonus, add an undo button for regular saving stops too to improve UX.

**Comment by SUPERCILEX** [comment]
@302scouting Could you please share more details about how to reproduce this bug?

There's a 3 minute timeout after which the stopwatch lap is thrown away and I've just confirmed that it's still working on Robot Scouter `v2.1.0`. AFAIK, the only way to stop a stopwatch is by a user pressing the button and the max time is 3 mins (180s). Are you seeing something different?

**Comment by 302scouting** [comment]
Hi Alex,

We are seeing the same timeouts that you mentioned above. We were just wondering if there was a way to have the app auto stop the stopwatch when the user exits out of a scout.

Thanks!

**Comment by SUPERCILEX** [comment]
@302scouting Oh, I think I get it! You're saying that if a scouter comes back to that team, the stopwatch will still be ticking and the only way to stop it is by pressing the button and thus saving a lap? If so, you can always delete a lap by long-pressing its cycle time (image attached below).

Do you think an improvement would be to make it so long-pressing the "Stop" button cancels the lap without saving it? Or maybe show a banner whenever a lap is added with a "Delete" button which can be used to delete the lap?

Deleting an existing lap:
![screenshot_20180120-195440](https://user-images.githubusercontent.com/9490724/35190685-f875486e-fe1b-11e7-9d0c-c4087d2519d7.png)

**Comment by SUPERCILEX** [comment]
@302scouting alrighty, I've gone ahead and added a bunch of undo banners and the option to cancel the stopwatch lap through a long-press, ensuring any possible scouting mistakes are easily rectifiable. Feel free to let me know if there's anything else you'd like to see improved! 😊
