### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Back800** [SUPERCILEX/Robot-Scouter#182]
### Step 1: Describe your environment
7 amazon kindle fire 7s
- Robot Scouter version: 2.1.0.5721
- Android OS version: 22
- User id: 1p7PK2sdlEf3utEmr9UXM58O8w53

### Step 2: Describe the problem:
There currently is no way to sort teams by event or individual scout sheets by match. Could you add a feature to do that perhaps with tba data?

**Comment by andrewda** [comment]
The basis for all of this isn't currently in the app (it doesn't fetch event or match data), but it will need to be done before #55.

**Comment by Back800** [comment]
Ok, I do know that FrcKrawler already does this so you might be able to take ideas from them.

**Comment by SUPERCILEX** [comment]
@Back800 Yup, I totally agree that incorporating matches into Robot Scouter is a must, and @andrewda is correct in that it will get lopped into #55. You can find a very much WIP doc [here](https://docs.google.com/document/d/1-bKe8ZgBIj3G6l3S-bVkubzXW65isfK_GBru-lPXHf0/edit?usp=sharing) and I'll post stuff on Chief Delphi and wherever else to get feedback once it's ready 👍.
