### ISSUE TITLE
Another Feature Request

### ISSUE THREAD

**Issue by Back800** [SUPERCILEX/Robot-Scouter#183]
### Step 2: Describe the problem:
Could you add a feature to have a timer in the background of scouting which starts when the scouter selects anything, logs all the selections they make, and ends when they select something such as finished climbing, this log would not be visible to the scouter but would be accessible in the exported spreadsheet.

**Comment by andrewda** [comment]
What would be the use case for something this?

**Comment by Back800** [comment]
Then the person analyzing the scouting info could get data for cycle times without having to rely on scouters filling out times in addition to what the robots are doing which we've found to be unreliable.

**Comment by SUPERCILEX** [comment]
@Back800 I'm not sure how that would be any more accurate: it still requires the scouter to enter data on-time and I know some of our scouters prefer to update counters and such in batches, not immediately when the robot does something...

**Comment by Back800** [comment]
Ok.
