### ISSUE TITLE
A Feature Request

### ISSUE THREAD

**Issue by Back800** [SUPERCILEX/Robot-Scouter#184]
### Step 2: Describe the problem:
At events, you can't rely on wifi and so we were wondering if you could add a feature to update the data between devices while competing using Bluetooth?

**Comment by SUPERCILEX** [comment]
Yup, a [similar feature is planned](https://github.com/SUPERCILEX/Robot-Scouter/issues/155). However, it wouldn't really be "syncing" the data in the conventional sense by storing it in the database on-device. Instead, it'll pull the latest data from all devices and do a merge to export the most up-to-date spreadsheet. That's the best I can do with the current infrastructure and I think it addresses your issue so I'm going to close this one.
