### ISSUE TITLE
Export as JSON

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#193]
People have been wanting a way to easily dump data into Tableau or process the data in some other friendly way. Since building out UI to decide what to export will be confusing and a pain, we'll just export the JSON _and_ the spreadsheet together. Since the number of files is getting messy, I'll move the exports into their own timestamped folder (later Auto Scout can name the folder after the competition).

Data format:
```js
{
  "2521": [
    {
      "name": "Scout 1",
      "metrics": {
        "id1": {
          "name": "Cubes in Switch",
          "type": "counter",
          "value": 5
        },
        "id2": { ... }
      }
    },
    { more scouts }
  ],
  "1540": [...]
}
```

**Comment by SUPERCILEX** [comment]
Lol, was just making an issue. Gonna update it with more details.

**Comment by SUPERCILEX** [comment]
@andrewda Is [this](https://github.com/SUPERCILEX/Robot-Scouter/files/1888050/raw.zip) good? I need you to actually do some data analysis on it because once I ship this, I need to do my best to not break API compatibility.

Anyway, gimme the green light and I'll 🚢 it! 👍

**Comment by andrewda** [comment]
Hmm, I don't really need the headers. Also, it might be better to turn the headers into "sections" in the JSON so it's something like this:

```
    {
      "name": "Q13",
      "metrics": {
        "b": {
          "type": "text",
          "name": "Name",
          "value": "Weston",
          "category": "Scout info"
        },
        "d": {
          "type": "boolean",
          "name": "Crossed baseline",
          "value": true,
          "category": "Auto"
        },
        "e": {
          "type": "list",
          "name": "Put cube in Switch",
          "value": "Successful",
          "category": "Auto"
        },
        ...etc
```

**Comment by SUPERCILEX** [comment]
Hmmm, you sure that's useful? I'm totally on board with filtering out the headers, but how would you use a `category` field?

**Comment by andrewda** [comment]
For displaying the data in sections. Showing an "Auto" section vs. a "Teleop" section might be a nice distinction.

**Comment by SUPERCILEX** [comment]
Also, I shouldn't be escaping characters such as `'`, right? Gson does that by default because they won't work in XHTML apparently.

**Comment by SUPERCILEX** [comment]
Would it also be fine if I moved all the existing data to a root `teams` ref? That would open up back-compat and future expansion possibilities...

**Comment by andrewda** [comment]
Yep that sounds good.

**Comment by SUPERCILEX** [comment]
Awesome sauce, we ready to ship [this](https://github.com/SUPERCILEX/Robot-Scouter/files/1891042/raw.zip)?
