### ISSUE TITLE
Add easy match number selection field

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#199]
Right now scouts are match agnostic. Make a new field to allow for the selection of a match, or entering the match number. This should also be the name of the scout instead of relying on the human to name the scout, which rarely gets done.

One option could be just having a dropdown with "Q", "QF", "SF", "F" with a text box next to it for the match number, followed by a conditional second text box if we're in "QF" or "SF" for the series number.

Another option could be getting match schedules from TBA and having a searchable dropdown of all the matches.

The latter will be needed for #55, so might be a good idea to spend the time on it anyways, but having the former as a backup in case there isn't any match schedule (or one couldn't be downloaded before we lost internet access) would be a good idea too.

**Comment by andrewda** [comment]
When selecting the match from a dropdown, only the matches in which that team plays should be shown.

**Comment by andrewda** [comment]
There should be UI to change it in case anything is wrong. Manual override but default it to what you think it is. And for the number follow TBA's naming: `qm54`, `qf2m2`, `sf1m2`, and `f1m1`.

**Comment by SUPERCILEX** [comment]
Nah to both. The match names needs to be human readble and the override won't be there. You'll be able to say the match number you're currently playing and you'll tell it when to move on to QF or F etc. Foolproof that way.

**Comment by SUPERCILEX** [comment]
Yeah, that'll only be for the JSON though. I've added that to the list, good idea. 👍
