### ISSUE TITLE
Link more closely with TBA API

### ISSUE THREAD

**Issue by andrewda** [SUPERCILEX/Robot-Scouter#200]
Also just a pre-requisite for #55, but something that can (and should) be done first as it's useful even without #55.

As discussed in #199, we should be able to download the match schedule from an event and select it from scouts.

There should also be a way to input the current event id being attended, and create a separate environment for this event, so it's in a different place and can be separated from previous data. Optional, because sometimes you want to stack data from events or see a summary of all of it. When you're in an event environment, download the teams that are going to be at that event and don't show any extra teams.

**Comment by SUPERCILEX** [comment]
@andrewda I'm doing this as an all or nothing so gonna close this in favor of #55. I also added your idea to support splitting the data into competition chunks which sounds really cool! 👍
