### ISSUE TITLE
Robot Scouter v 2.3.1.5823 Problems when press the Reset tutorial feature, and issues when turning on night mode in android 7.0

### ISSUE THREAD

**Issue by ammarraisafti** [SUPERCILEX/Robot-Scouter#206]
#### Expected behavior
After enabling night mode, then press the Reset tutorial feature. Supposedly, night mode is not disabled. And when trying to re-enable night mode, the ability to activate night mode should be possible.

#### Actual behavior
After enabling night mode, then press the Reset tutorial feature. Night mode suddenly disabled. And when try to re-enable it, night mode can not be enabled. Although I have tried to do it repeatedly, but unfortunately the same problem still occurs.

#### How to reproduce
* Launch app.
* Click the left selection option, to display some menus and select the Settings feature.
* Select the Night mode feature, and select the option ON.
* Press the Reset tutorial feature. _**Night mode disabled.**_
* Log back into the Settings feature, select Night mode feature, and select the option ON._**Night mode can not be activated.**_

**Browser: Samsung Galaxy S6 edge**
**Operating system: Nougat 7.0**
**App version: 2.3.1.5823**

#### Recording Of The Bug
https://youtu.be/KijGFa_0Cko

**Comment by SUPERCILEX** [comment]
Thanks for the bug report! This has been fixed in the [alpha channel](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/README.md#psst-) (available in a few hours). In the meantime, you can just restart Robot Scouter to clear that bad local state.
