### ISSUE TITLE
Tap export result does not work in notification bar

### ISSUE THREAD

**Issue by Icramss** [SUPERCILEX/Robot-Scouter#208]
How to reproduce
- run the app
- Try scouting
- if it is finished, please export
- Tap 3 lines on the left side of the top to export
- Tap export all item
- wait a moment in processing export
- when the export is finished you will see the export in the notification bar.
- Tap on the export result notification to see it.
- you will not see it. It does not work

**Comment by SUPERCILEX** [comment]
@Icramss Can you share the debug info mentioned in the issue template? Also, can you show a screenshot of what you mean by "you will not see it?"

**Comment by Icramss** [comment]
![20180603_015859.gif](https://cdn.steemitimages.com/DQmWMx8Ptwc24KAQiZyad4v6p2waSGDhqjP8KSd5f42mpZz/20180603_015859.gif)

Tap export results not working

**Comment by SUPERCILEX** [comment]
Oh, I see. You're running on Android pre-Nougat. If you go to your file explorer, you'll find the files in `Documents`.

I agree that this is a bad UX though so I'll make that notification link directly to the file explorer. Thanks for the idea! 😊

**Comment by Icramss** [comment]
Is that not a bug from your app?

**Comment by SUPERCILEX** [comment]
No, you can read about the [`Bundled notifications`](https://developer.android.com/about/versions/nougat/android-7.0#notification_enhancements) section. Here's what it looks like on API 24+:
![screenshot_20180602-120744](https://user-images.githubusercontent.com/9490724/40879961-d006c47a-665d-11e8-89d7-c22aaa4c93cb.png)

**Comment by Icramss** [comment]
Yeah. Essentially you have to add the work operation I mean. With Tap on notification, the app can go to explore file

**Comment by SUPERCILEX** [comment]
Huh, I remember why I hadn't done this yet: Android doesn't have a standard browse action. Some popular file managers like ES and Solid support what I've done, but for others, you'll just get a picker popup that tells you pick a file browser app.

The fix will be available in the [alpha channel](https://github.com/SUPERCILEX/Robot-Scouter/blob/master/README.md#psst-) in the coming hours.
