### ISSUE TITLE
Export results can not be found in document file manager

### ISSUE THREAD

**Issue by Icramss** [SUPERCILEX/Robot-Scouter#210]
Recording of the bug 

https://youtu.be/KWWZX5dH84A

Device 6.0.1

**Comment by SUPERCILEX** [comment]
That's weird. Can you share the debug info mentioned in the issue template? (Go into settings and tap `Version`)

**Comment by SUPERCILEX** [comment]
Oh wait, nevermind. You're looking at the Documents _category_. That's not something I can control and your file browser doesn't consider Excel spreadsheets to be a document I guess. If you look at [this spot](https://youtu.be/KWWZX5dH84A?t=13s) in your video, you'll see near the bottom that there's a folder called Documents. That's where you'll find the exports.

Please let me know if that isn't it!
