### ISSUE TITLE
proposal logo for Robot Scooter application

### ISSUE THREAD

**Issue by ammarraisafti** [SUPERCILEX/Robot-Scouter#211]
Hi admin, I would like to offer a cool new design and cool logo for Scouter Robot app. If you like and can accept it.

You simply reply to this proposal, I will gladly send you a new logo of this file and I can give you some variations for this app, thank you!

![amazing](https://user-images.githubusercontent.com/37721970/41193825-75eaa0bc-6c3c-11e8-8ae5-5fe404821089.png)

**Comment by SUPERCILEX** [comment]
Hi,
Thanks for the contribution! Unfortunately, I prefer flat, material design style iconography, so this logo wouldn't fit with the rest of my app's theme.

**Comment by ammarraisafti** [comment]
Can I create a logo like you want?

Pada tanggal Min, 10 Jun 2018 00:57, Alex Saveau <notifications@github.com>
menulis:

**Comment by ammarraisafti** [comment]
I will try to redesign your logo now, according to the principle of
material design principles. And will tell you when it's done.

Pada tanggal Min, 10 Jun 2018 01:23, Alex Saveau <notifications@github.com>
menulis:
