### ISSUE TITLE
Add scout timestamps to JSON export

### ISSUE THREAD

**Issue by Jamdan2** [SUPERCILEX/Robot-Scouter#251]
**Is your feature request related to a problem? Please describe.**

It would be nice if scouts got timestamped when created so when viewing the data it could be chronologically ordered. Or you could provide the option to do so

**Describe the solution you'd like**

When creating a new template a checkbox that says 'include timestamp' or date in the scout, so that it appears in the exported data

**Describe alternatives you've considered**

I guess if you indexed the scouts that would work too but a timestamp provides more info
I know this can be done with naming conventions or adding a 'match number' metric, but it would be so much cooler to have it be automatic 😎

**Comment by SUPERCILEX** [comment]
I'm confused... that's how it works already. In the app, the newest scouts appear first (descending order starting from the left). And when the scouts are exported, they appear chronologically (ascending order) from left to right.

Why would you want the timestamp for each scout in the export? Not sure I see the usefulness. Though I could definitely add it to the JSON export, did you mean that?

**Comment by Jamdan2** [comment]
Yeah, I really just care about the json export, I just figured you might want to do the same with the spreadsheet.

**Comment by Jamdan2** [comment]
If the timestamp on the spreadsheet wouldn't be useful then nm that then

**Comment by SUPERCILEX** [comment]
Oh cool, that's makes sense. 👍 When you said export, I thought you meant spreadsheet.

I'll probably be able to ship an alpha tomorrow, though the JSON array is already ordered chronologically if that's helpful.
