### ISSUE TITLE
Add shortName property to metrics

### ISSUE THREAD

**Issue by Jamdan2** [SUPERCILEX/Robot-Scouter#252]
**Is your feature request related to a problem? Please describe.**
When entering data into a table it is desirable to have short metric names in order to
keep the table condensed. However, shorter names sacrifice clarity.

**Describe the solution you'd like**
Can metrics have an additional key called shortName that gets specified in the template?

**Describe alternatives you've considered**
An alternative would be for me to manually transform the data and add shortName to each metric myself. It would be better to support it in here though.

**Additional context**
Thats it

**Comment by SUPERCILEX** [comment]
I'm not sure I see the use case. Why can't you force line wraps? Or truncate it with a little tooltip to see the expanded version? Personally, I'd like to encourage short names by default once I get around to #192.

**Comment by Jamdan2** [comment]
I already do wrap the text, and it still needs to span 200 pixels per column. I could substring it then use a tool tip, but short names would be a better solution.

**Comment by Jamdan2** [comment]
Btw I got this idea from logger pro so it actually is pretty normal to give data an abbreviated name when analyzing it.

**Comment by SUPERCILEX** [comment]
Hmmm, those are fair points, but I think I'm going to have to say no:
- I want to prioritize spreadsheets as opposed to the JSON.
- Where would the user enter this information? The template editor is already kinda messy and I don't want to add a dialog just for the short name. Also, having two different name fields makes creating and maintaining templates much harder and more confusing.
- There are a ton of post-processing options: you could make the column resizable, truncate it, manually map the known IDs to short names, etc.
