### ISSUE TITLE
Add ability to choose from multiple different scouting templates when creating a new scout

### ISSUE THREAD

**Issue by SUPERCILEX** [SUPERCILEX/Robot-Scouter#82]
This would make is super easy to switch between doing a pit scout vs doing a stand scout.

# Table of contents

- [Intro](#intro)
- [TODO](#todo)
- [Sample data structure](#sample-data-structure)
- [Tech spec](#tech-spec)
  - [Assumptions](#assumptions)
  - [Adding a new template](#add-template)
  - [Adding a new scout](#add-scout)
  - [Setting the default template](#set-default-template)
  - [Opening the template editor from a team](#open-template-editor)
  - [Spreadsheet exporting](#exporting)

# <a name="intro">Intro</a>

This PR adds support for multiple scouting templates and is one of the biggest refactors in Robot Scouter history along with supporting tablet mode.

So far, the UI is all setup to support editing multiple templates, but there are still numerous features to work on such as handling the addition of scouts and new templates, changing the default template, supporting cross-account sharing, etc.

Thus, a significant amount of thought is required to get this feature right the first time around. The following document outlines the technical details necessary to support multiple scouting templates.

# <a name="todo">TODO</a>

UI features needed to fully support multiple templates will be developed in parallel with this PR:
- [x] Navigation drawer with an entry to edit scouting templates probably just called `Scout template editor` with the "pen edit" icon (#115)
- [x] Settings activity to [change the default template](#set-default-template) (#131)
  - That setting should also be available in the template editor. For example, a menu option such as `Set current template as default`

In addition, this PR still needs some other changes before it’s ready to be merged:
- [x] Reorganize the `template-indices` in the database. At the moment, it’s under the `users` ref, but we should separate it out as we do with the team and scout indices.
- [x] [Adding a new template](#add-template)
- [x] [Adding a new scout](#add-scout)
  - [x] with [long-press](#add-scout-long-press)
- [x] [Opening the template editor](#open-template-editor) from a team
- [x] Spreadsheet [exporting](#exporting)
- [x] Template [smart suggest](#template-smart-suggest)
- [x] Sharing individual templates with other Robot Scouter accounts
- [x] Add Firebase App Indexing support to templates
- [x] Fix adding metric bugs by getting the currently active template from the tab keys pager adapter

# <a name="sample-data-structure">Sample data structure</a>

**Note:** only relevent refs and fields are shown.

```js
{
    "teams/$key": {
        "templateKey": "key",
        "scouts": {
            "key1": {
                "name": "Foobar",
                "templateKey": "key",
                "metrics": { … }
            }
            // …
        }
        // …
    },
    "templates/$key": {
        "name": "Foobar",
        "metrics": { … }
    },
    "template-indices/$uid": {
        "key1": true
        // …
    },
    "users/$uid": {
        "templateLog": [ "key1", "key2", "key3"],
        "prefs": {
            "defaultTemplateKey": "key"
        }
    }
}
```

# <a name="tech-spec">Tech spec</a>

### Every `templateKey` in the team model is guaranteed to be using the default template

This ensures that when individual teams are shared with other Robot Scouter users, they will be using the right template.

#### Implementation details

On app boot in the database initializer, add a listener for `ADDED` and `CHANGED` team events.

- If the team `templateKey != null`
  - If the template is owned by user e.g. it can be found under `template-indices/$uid`
    - If that template is the default e.g. the team template key and the `users/$uid/prefs/defaultTemplateKey` are identical -> leave the team template key alone
    - If the team template key isn’t the default -> update the team key to the default
  - If the template key isn’t owned by the user
    - If the `template data != null` -> leave it alone
    - If the `template data == null` -> update it to the default. We need to do this to guarantee data consistency when other devices are offline or the team is shared with another user. For example, say an online device deletes a template, but an offline one continues adding teams with the deleted template. When everything is synced up, we will end up with teams that have template keys pointing to non-existent templates. The same thing will happen if another user deletes a template since that user won’t have access to the other user’s teams to update them.
- If the team `templateKey == null`
  - If the user has templates i.e. `users/$uid/prefs/defaultTemplateKey != null` -> add the default template key to the team
  - If the user does not have a template -> add key for public match scouting template

### `users/$uid/prefs/defaultTemplateKey` is never `null` if the user has templates

Add a listener on app boot.

- If `defaultTemplateKey == null`
  - If the user has templates, something very wrong happened so just set the default to the fist template key in the user's list
  - If the user does not have templates, just set it to the public match scouting template for now. In future releases, we might try to be smarter and start with a pit scout template and then transition to using the match scout template, but being dumb will have to do for now.
- If `defaultTemplateKey != null` -> just leave it alone

## <a name="add-template">Adding a new template</a>

When choosing the template for the template (inception! 😀), we should show the user a dialog with 3 options to choose from as the base template to start with:
1. The match scouting template
2. The pit scouting template
3. An empty template to start fresh

#### Implementation details

- If there are no existing templates, set the `templateKey` for all teams whose keys are `null`
- If there’s an existing template, don’t touch the teams since they should have been processed by our [assumptions](#assumptions).

## <a name="add-scout">Adding a new scout</a>

Thanks to our [earlier assumptions](#assumptions), adding a new scout will have minimal performance impacts and low bug probability. We simply take the team’s `templateKey` and get the template from there.

Since we also support a long press to use a non-default template, we'll just take whatever key is passed in through there.

### <a name="add-scout-long-press">Adding a new scout with a long-press</a>

This shouldn't be too hard UI wise, we'll just add a context menu to the `TeamViewHolder` and `ScoutListFragment` "add scout" buttons. The title will be something like `Choose scout template` and each item will be the template name (or `Template #` if it doesn't have one). In addition, we should ensure the default template is the first item and has a 🌟 icon next to it.

However, UX wise it's going to be more complicated. We'll have to figure out how to add a progress bar or something to indicate that the template names are loading.

## <a name="set-default-template">Setting the default template</a>

Easy peesy, we'll just change every team `templateKey` whose key is owned by the user to be the new default template key.

### <a name="template-smart-suggest">Smart suggest (I know, so 🧀! 😂)</a>

We'll want to add a `users/$uid/templateLog` object which contains a list of the three most recent template keys used when adding scouts. Whenever a scout is added we'll check that list and if all three keys are the same i.e. the template was used three times in a row, we'll show a dialog suggesting to change the default template if those keys weren't already pointing to the default template.

As for the dialog itself, `Yes` will change the default. Either way, we'll clear the list so we start counting all over again.

**Better idea:** in the add scout with long-press dialog (`ScoutTemplateSelectorDialog`), we'll add a checkbox that says "Set as default" so we don't annoy the user and give them more choice at the same time.

## <a name="open-template-editor">Opening the template editor from a team</a>

- If the `templateKey != null`, simply deep link to that template
  - If the template isn't owned by the user -> we'll have to inject it into the beginning of the list so it's the first template showing. Then we should also show some SnackBar saying the user doesn't own the template so it won't show up under normal circumstances.
  - Otherwise, we're good
- If it’s null, create a new template using the [same rules as above](#add-template)

## <a name="exporting">Spreadsheet exporting</a>

We'll export each template spawn in a different file meaning each group of scouts stemming from one template key will be exported as a single file and etc. for the other groups of scouts. To do this we'll have to add a "templateKey" field to each scout so we can properly group them. If there are multiple groups, each file name will be formatted like so: `[$templateName]_$fileName.$extension`. `templateName` will be all caps and spaces will be converted to underscores.

**Comment by blake1029384756** [comment]
Could you add the ability for the template to be named for easier identification?

**Comment by vannaka** [comment]
It should have a way to specify a scout as a pit scout and limit you you to one pit scout. You would still be able to do as many match scouts as you wanted. Then the spreadsheet would include the data for each team gathered from both types. This would allow the spreadsheet to have columns for things like drive train type.  Thus eliminating the need to reenter the data in the pregame section that is in the default template now.

**Comment by SUPERCILEX** [comment]
@blake1029384756 Yes, that's the plan! Unfortunately, I didn't have the foresight to put the metrics under a `metrics` ref (like I did for each scout) meaning I can't add this feature without breaking backwards compatibility. That's why I marked it as `2.0` feature because I think I messed in a lot of places and will have to make a ton of backwards incompatible changes to get it working properly.

@vannaka Hmmm, that didn't occur to me. Do you think people would ever want to have multiple pit scouts? I really like the idea of having only one pit scout because it would simplify things significantly. And yeah, it will definitely be nice to not have to enter pre-game data every match! 😄

@blake1029384756 @vannaka Thanks for the great ideas! 🚀 I've been focusing on stability lately so I haven't had much time to start thinking about the next big features, but I'm glad to see other people are looking into this.

This conversation also made me realize that I need a way to force people to be on the latest version of the app or bad things will happen so I did that in 2bd5305c9f3993f00b1ac0dc203c857c83f858da. Thanks!

**Comment by SUPERCILEX** [comment]
@blake1029384756 @vannaka multi-templates is officially live in the alpha channel! 😄
