### ISSUE TITLE
Crash when creating new entry

### ISSUE THREAD

**Issue by blake1029384756** [SUPERCILEX/Robot-Scouter#97]
When I create a new team entry to scout, the app crashes. However my old entries work as expected. 

Here is a logcat of the crash
[scouter.txt](https://github.com/SUPERCILEX/Robot-Scouter/files/887886/scouter.txt)

* Robot Scouter version: 1.0.2.5281
* Android OS version: 23
* User id: wQPZykRqf9MmbHjgXuflEJ3q0G42
* Current scout template key: null

**Comment by SUPERCILEX** [comment]
@blake1029384756 Thanks again! I haven't seen this crash myself, but I think I fixed the root cause in 	5eeda49.

I'll post another comment when the update goes live so you can try it out.

**Comment by SUPERCILEX** [comment]
@blake1029384756 `v1.0.2.5285` is available in the beta channel. Please tell me if you're still having issues.

**Comment by blake1029384756** [comment]
@supercilex thanks for the fix, it has solved my problem!
